# https://docs.astral.sh/uv/guides/integration/github/#setting-up-python
name: Test

on:
  push

jobs:

  Test:
    name: python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"


    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.4"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install playwright
        run: |
          source .venv/bin/activate
          playwright install-deps
          playwright install

      - name: Run tests
        run: uv run pytest tests
